export const NEXT_PUBLIC_CLOUDINARY_PRESET_NAME =
  process.env.NEXT_PUBLIC_CLOUDINARY_PRESET_NAME || "ecom_admin";

export const NEXT_PUBLIC_STRIPE_PUBLIC_KEY =
  process.env.NEXT_PUBLIC_STRIPE_PUBLIC_KEY;

export const NEXT_PUBLIC_STRIPE_SECRET_KEY =
  process.env.NEXT_PUBLIC_STRIPE_SECRET_KEY;
